Sports News Website/Controllers/AthleteController.cs
using DataAccess.Repositories;
using DataStructure;
using Sports_News_Website.CustomAttributes;
using Sports_News_Website.DTOs;
using Sports_News_Website.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sports_News_Website.Controllers
{
    [CustomAuthentication]
    public class AthleteController : BaseController<Athletes>
    {
        public AthleteController() : base(UnitOfWork.UOW.AthleteRepository)
        {

        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Create()
        {
            List<Sports> allSports = UnitOfWork.UOW.SportRepository.GetAll();
            SelectList selectListItems = new SelectList(allSports, "ID", "Name");
            ViewData["SportsList"] = selectListItems;
            return base.Create();
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Create(AthleteViewModel athleteViewModel)
        {
            Athletes athlete = new Athletes();
            if (ModelState.IsValid)
            {
                List<Sports> allSports = UnitOfWork.UOW.SportRepository.GetAll();
                Sports currentSport = allSports.Where(x => x.ID == athleteViewModel.Sport).FirstOrDefault();
                athlete.ID = athleteViewModel.ID;
                athlete.Name = athleteViewModel.Name;
                athlete.Sport = currentSport;
                return base.Create(athlete);
            }
            else
            {
                List<Sports> allSports = UnitOfWork.UOW.SportRepository.GetAll();
                SelectList selectListItems = new SelectList(allSports, "ID", "Name");
                ViewData["SportsList"] = selectListItems;
                return View(athlete);
            }
        }
        [HttpGet]
        public new ActionResult Read()
        {
            return base.Read();
        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Update(int id)
        {
            List<Sports> allSports = UnitOfWork.UOW.SportRepository.GetAll();
            SelectList selectListItems = new SelectList(allSports, "ID", "Name");
            ViewData["SportsList"] = selectListItems;
            return base.Update(id);
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Update(UpdateAthleteViewModel updateAthleteViewModel)
        {
            List<Sports> allSports = UnitOfWork.UOW.SportRepository.GetAll();
            Sports currentSport = allSports.Where(x => x.ID == updateAthleteViewModel.Sport).FirstOrDefault();
            List<Athletes> allAthletes = UnitOfWork.UOW.AthleteRepository.GetAll();
            Athletes currentAthlete = allAthletes.Where(x => x.ID == updateAthleteViewModel.ID).FirstOrDefault();
            SelectList selectListItems = new SelectList(allSports, "ID", "Name");
            ViewData["SportsList"] = selectListItems;
            if (ModelState.IsValid)
            {
                if (updateAthleteViewModel.Sport != null)
                {
                    currentAthlete.Sport = currentSport;
                }
                currentAthlete.ID = updateAthleteViewModel.ID;
                currentAthlete.Name = updateAthleteViewModel.Name;
                return base.Update(currentAthlete);
            }
            return View(currentAthlete);
        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Delete(int? id)
        {
            return base.Delete(id);
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Delete(int id)
        {
            return base.Delete(id);
        }
    }
}

Sports News Website/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.Repositories;
using DataStructure;
using Sports_News_Website.CustomAttributes;
using Sports_News_Website.DTOs;
using Sports_News_Website.Services;
using Sports_News_Website.ViewModels;
using static System.Net.WebRequestMethods;

namespace Sports_News_Website.Controllers
{
    [CustomAuthentication]
    public class NewsController : BaseController<News>
    {
        public NewsController() : base(UnitOfWork.UOW.NewsRepository)
        {

        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Create()
        {
            return base.Create();
        }
        [HttpPost]
        [CustomAuthorization]
        public ActionResult Create(NewsViewModel newsViewModel)
        {
            News news = new News();
            if (ModelState.IsValid)
            {
                if (newsViewModel.Photo != null)
                {
                    ImageUploadService imageUploadService = new ImageUploadService();
                    bool isImageValid = imageUploadService.CheckImageExtension(newsViewModel);
                    if (isImageValid == true)
                    {
                        string fileName = imageUploadService.UploadImage(newsViewModel);
                        news.Photo = fileName;
                    }
                    else
                    {
                        ModelState.AddModelError("PhotoContentTypeError", "The file you are trying to upload is not an image!");
                        return View(newsViewModel);
                    }
                }
                news.ID = newsViewModel.ID;
                news.Title = newsViewModel.Title;
                news.Content = newsViewModel.Content;
                List<Users> allUsers = UnitOfWork.UOW.UserRepository.GetAll();
                Users currentUser = allUsers.Where(x => x.ID == SessionDTO.ID).FirstOrDefault();
                news.User = currentUser;
                return base.Create(news);
            }
            else
            {
                return View(newsViewModel);
            }
        }
        [HttpGet]
        public new ActionResult Read()
        {
            return base.Read();
        }
        [HttpGet]
        public new ActionResult Details(int id)
        {
            News currentNews = UnitOfWork.UOW.NewsRepository.GetByID(id);
            var tupleModel = new Tuple<News, List<Comments>>(currentNews,
                currentNews.Comments);
            System.Web.HttpContext.Current.Session["CurrentNewsID"] = currentNews.ID;
            NewsDTO.NewsID = currentNews.ID;
            return View(tupleModel);
        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Update(int id)
        {
            return base.Update(id);
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Update(NewsViewModel newsViewModel)
        {
            News news = new News();
            List<News> allNews = UnitOfWork.UOW.NewsRepository.GetAll();
            News currentNews = allNews.Where(x => x.ID == newsViewModel.ID).FirstOrDefault();
            if (newsViewModel.Photo == null)
            {
                news.Photo = currentNews.Photo;
            }
            if (newsViewModel.Photo != null)
            {
                string fileName = newsViewModel.Photo.FileName; // the photo that is uploaded
                string targetFolder = System.Web.HttpContext.Current.Server.MapPath("~/Photo"); // the folder where the photo needs to go
                string targetPath = Path.Combine(targetFolder, fileName); // the whole path
                newsViewModel.Photo.SaveAs(targetPath); // saving the photo
                news.Photo = fileName;
            }
            if (ModelState.IsValid)
            {
                news.ID = newsViewModel.ID;
                news.Title = newsViewModel.Title;
                news.Content = newsViewModel.Content;
                return base.Update(news);
            }
            else
            {
                return View(news);
            }
        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Delete(int? id)
        {
            return base.Delete(id);
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Delete(int id)
        {
            List<News> allNews = UnitOfWork.UOW.NewsRepository.GetAll();
            News currentNews = allNews.Where(x => x.ID == id).FirstOrDefault();
            /* Adding .ToList() method in the foreach loop for the collection (the list) because it was giving the error 
               'Collection was modified; enumeration operation may not execute.'.
            After checking in stackoverflow, .NET doesn't support collections to be enumerated and modified at the same
            time, that is why an exception was given before.*/
            /* checking for null value in the comments 
                (if we don't check, there will be an exception thrown)*/
            if (currentNews.Comments != null)
            {
                foreach (Comments comment in currentNews.Comments.ToList())
                {
                    UnitOfWork.UOW.CommentRepository.Delete(comment.ID);
                }
            }
            return base.Delete(id);
        }
    }
}

Sports News Website/Controllers/SportController.cs
using DataAccess.Repositories;
using DataStructure;
using Sports_News_Website.CustomAttributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Sports_News_Website.Controllers
{
    [CustomAuthentication]
    public class SportController : BaseController<Sports>
    {
        public SportController() : base(UnitOfWork.UOW.SportRepository)
        {

        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Create()
        {
            return base.Create();
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Create(Sports sport)
        {
            return base.Create(sport);
        }
        [HttpGet]
        public new ActionResult Read()
        {
            return base.Read();
        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Update(int id)
        {
            return base.Update(id);
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Update(Sports sport)
        {
            return base.Update(sport);
        }
        [HttpGet]
        [CustomAuthorization]
        public new ActionResult Delete(int? id)
        {
            return base.Delete(id);
        }
        [HttpPost]
        [CustomAuthorization]
        public new ActionResult Delete(int id)
        {
            return base.Delete(id);
        }
    }
}

Sports News Website/Views/Shared/InsufficientPermission.cshtml
@{
    ViewBag.Title = "InsufficientPermission";
}

<h1>You do not have permission to enter this page !</h1>

Sports News Website/Views/Shared/Login.cshtml
@model Sports_News_Website.Models.Users

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Users</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Read")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Sports News Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @using Sports_News_Website.DTOs
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body background="~/Photo/Sports-Wallpapers.jpg" style="color: white">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sports News Website", "Read", "News", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("News", "Read", "News")</li>
                    <li>@Html.ActionLink("Sports", "Read", "Sport")</li>
                    <li>@Html.ActionLink("Athletes", "Read", "Athlete")</li>
                    <li>@Html.ActionLink("Users", "Read", "Users")</li>
                    @if (SessionDTO.ID == 0)
                    {
                        <li>@Html.ActionLink("Login", "Login", "Users")</li>
                        <li>@Html.ActionLink("Register", "Register", "Users")</li>
                    }
                    @if (SessionDTO.ID != 0)
                    {
                        <li>Hello, @SessionDTO.Username, @SessionDTO.ID, You have Admin privileges : @SessionDTO.IsAdmin</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Users")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>